name: Setup java
description: Setup java

runs:
  using: "composite"
  steps:
    - name: Replace gradle distribution url
      run: sed -i 's/-all.zip/-bin.zip/' gradle/wrapper/gradle-wrapper.properties
      shell: bash
