name: Release patch

on:
  workflow_dispatch:

jobs:
  test:
    name: Release patch version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup gradle
        uses: ./.github/actions/setup-gradle
      - name: Increment patch version
        run: ./gradlew incrementPatchVersion
        shell: bash
      - name: Prepare gradle secrets
        run: echo 'gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}' > $HOME/.gradle/gradle.properties && echo 'gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}' >> $HOME/.gradle/gradle.properties
        shell: bash
      - name: Publish
        run: ./gradlew publishPlugins
        shell: bash
