name: Release minor

on:
  workflow_dispatch:

jobs:
  test:
    name: Release minor version
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup gradle
        uses: ./.github/actions/setup-gradle
      - name: Increment minor version
        run: ./gradlew incrementMinorVersion
        shell: bash
      - name: Publish
        run: ./gradlew publishPlugins
        shell: bash
