name: Release

on:
  push:
    branches:
      - feature/3/GA-setup

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo
        run: echo 1
        shell: bash
